/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ChopinCore } from "../core.js";
import { encodeJSON } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import * as components from "../models/components/index.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Sequence operation
 *
 * @remarks
 * Wait until it's our turn for `domain`.
 *     pub async fn sequence(&self, domain: &str, request_id: &str) {
 *         let domain = domain.to_owned();
 *         let request_id = request_id.to_owned();
 *
 *         let mut map = self.domain_queues.lock().await;
 *         let queue = map.entry(domain.clone()).or_insert(DomainQueue {
 *             active: false,
 *             waiting: VecDeque::new(),
 *         });
 *
 *         if !queue.active {
 *             queue.active = true;
 *             println!("[Sequencer] Domain={}, RequestId={} is now active", domain, request_id);
 *         } else {
 *             println!("[Sequencer] Domain={}, RequestId={} is enqueued", domain, request_id);
 *             let (tx, rx) = oneshot::channel();
 *             queue.waiting.push_back(tx);
 *             drop(map);
 *
 *             // Wait until unblocked by .done()
 *             let _ = rx.await;
 *             println!("[Sequencer] Domain={}, RequestId={} is now active", domain, request_id);
 *         }
 *     }
 *
 *     /// Signal that the active request is done for `domain`. If another is waiting,
 *     /// that one is unblocked and becomes active.
 *     pub async fn done(&self, domain: &str) {
 *         let domain = domain.to_owned();
 *         let mut map = self.domain_queues.lock().await;
 *         if let Some(queue) = map.get_mut(&domain) {
 *             if let Some(tx) = queue.waiting.pop_front() {
 *                 let _ = tx.send(());
 *             } else {
 *                 // No one waiting; mark domain as idle
 *                 queue.active = false;
 *             }
 *         }
 *     }
 * }
 *
 * //
 * // ------------------
 * // Request/Response Models
 * // ------------------
 * //
 *
 * #[derive(Serialize, Deserialize)]
 * struct ErrorResponse {
 *     message: String,
 * }
 *
 * #[derive(Deserialize, Serialize)]
 * struct SequenceRequest {
 *     domain: String,
 *     request_id: String,
 * }
 *
 * #[derive(Deserialize, Serialize)]
 * struct DoneRequest {
 *     domain: String,
 * }
 *
 * //
 * // ------------------
 * // OpenAPI Specification
 * // ------------------
 * //
 *
 * /// Returns the OpenAPI specification as a JSON object
 * async fn openapi_json() -> Json<serde_json::Value> {
 *     let openapi_spec = serde_json::json!({
 *             "openapi": "3.0.3",
 *             "info": {
 *                 "title": "Sequencer API",
 *                 "description": "API for sequencing domain operations",
 *                 "version": "0.1.0",
 *                 "contact": {
 *                     "name": "API Support",
 *                     "email": "support@example.com"
 *                 }
 *             },
 *             "paths": {
 *                 "/sequence": {
 *                     "post": {
 *                         "summary": "Sequence operation",
 *                         "description": "Wait until it's our turn for `domain`.
 *     pub async fn sequence(&self, domain: &str, request_id: &str) {
 *         let domain = domain.to_owned();
 *         let request_id = request_id.to_owned();
 *
 *         let mut map = self.domain_queues.lock().await;
 *         let queue = map.entry(domain.clone()).or_insert(DomainQueue {
 *             active: false,
 *             waiting: VecDeque::new(),
 *         });
 *
 *         if !queue.active {
 *             queue.active = true;
 *             println!(\"[Sequencer] Domain={}, RequestId={} is now active\", domain, request_id);
 *         } else {
 *             println!(\"[Sequencer] Domain={}, RequestId={} is enqueued\", domain, request_id);
 *             let (tx, rx) = oneshot::channel();
 *             queue.waiting.push_back(tx);
 *             drop(map);
 *
 *             // Wait until unblocked by .done()
 *             let _ = rx.await;
 *             println!(\"[Sequencer] Domain={}, RequestId={} is now active\", domain, request_id);
 *         }
 *     }
 *
 *     /// Signal that the active request is done for `domain`. If another is waiting,
 *     /// that one is unblocked and becomes active.
 *     pub async fn done(&self, domain: &str) {
 *         let domain = domain.to_owned();
 *         let mut map = self.domain_queues.lock().await;
 *         if let Some(queue) = map.get_mut(&domain) {
 *             if let Some(tx) = queue.waiting.pop_front() {
 *                 let _ = tx.send(());
 *             } else {
 *                 // No one waiting; mark domain as idle
 *                 queue.active = false;
 *             }
 *         }
 *     }
 * }
 *
 * //
 * // ------------------
 * // Request/Response Models
 * // ------------------
 * //
 *
 * #[derive(Serialize, Deserialize)]
 * struct ErrorResponse {
 *     message: String,
 * }
 *
 * #[derive(Deserialize, Serialize)]
 * struct SequenceRequest {
 *     domain: String,
 *     request_id: String,
 * }
 *
 * #[derive(Deserialize, Serialize)]
 * struct DoneRequest {
 *     domain: String,
 * }
 *
 * //
 * // ------------------
 * // OpenAPI Specification
 * // ------------------
 * //
 *
 * /// Returns the OpenAPI specification as a JSON object
 * async fn openapi_json() -> Json<serde_json::Value> {
 *     let openapi_spec = serde_json::json!({
 *         \"openapi\": \"3.0.3\",
 *         \"info\": {
 *             \"title\": \"Sequencer API\",
 *             \"description\": \"API for sequencing domain operations\",
 *             \"version\": \"0.1.0\",
 *             \"contact\": {
 *                 \"name\": \"API Support\",
 *                 \"email\": \"support@example.com\"
 *             }
 *         },
 *         \"paths\": {
 *             \"/sequence\": {
 *                 \"post\": {
 *                     \"summary\": \"Sequence a request for a domain\",
 *                     \"description\": \"Request will be queued if there's already an active request for the domain\",
 *                     \"operationId\": \"sequence\",
 *                     \"tags\": [\"sequencer\"],
 *                     \"security\": [{\"BearerAuth\": []}],
 *                     \"requestBody\": {
 *                         \"required\": true,
 *                         \"content\": {
 *                             \"application/json\": {
 *                                 \"schema\": {
 *                                     \"$ref\": \"#/components/schemas/SequenceRequest\"
 *                                 }
 *                             }
 *                         }
 *                     },
 *                     \"responses\": {
 *                         \"200\": {
 *                             \"description\": \"Request has been sequenced\",
 *                             \"content\": {
 *                                 \"text/plain\": {
 *                                     \"schema\": {
 *                                         \"type\": \"string\",
 *                                         \"example\": \"OK\"
 *                                     }
 *                                 }
 *                             }
 *                         },
 *                         \"401\": {
 *                             \"description\": \"Unauthorized - Invalid or missing API key\",
 *                             \"content\": {
 *                                 \"application/json\": {
 *                                     \"schema\": {
 *                                         \"$ref\": \"#/components/schemas/ErrorResponse\"
 *                                     }
 *                                 }
 *                             }
 *                         }
 *                     }
 *                 }
 *             },
 *             \"/done\": {
 *                 \"post\": {
 *                     \"summary\": \"Mark a domain's active request as done\",
 *                     \"description\": \"If other requests are waiting, the next one will become active\",
 *                     \"operationId\": \"done\",
 *                     \"tags\": [\"sequencer\"],
 *                     \"security\": [{\"BearerAuth\": []}],
 *                     \"requestBody\": {
 *                         \"required\": true,
 *                         \"content\": {
 *                             \"application/json\": {
 *                                 \"schema\": {
 *                                     \"$ref\": \"#/components/schemas/DoneRequest\"
 *                                 }
 *                             }
 *                         }
 *                     },
 *                     \"responses\": {
 *                         \"200\": {
 *                             \"description\": \"Domain marked as done\",
 *                             \"content\": {
 *                                 \"text/plain\": {
 *                                     \"schema\": {
 *                                         \"type\": \"string\",
 *                                         \"example\": \"OK\"
 *                                     }
 *                                 }
 *                             }
 *                         },
 *                         \"401\": {
 *                             \"description\": \"Unauthorized - Invalid or missing API key\",
 *                             \"content\": {
 *                                 \"application/json\": {
 *                                     \"schema\": {
 *                                         \"$ref\": \"#/components/schemas/ErrorResponse\"
 *                                     }
 *                                 }
 *                             }
 *                         }
 *                     }
 *                 }
 *             },
 *             \"/health\": {
 *                 \"get\": {
 *                     \"summary\": \"Health check endpoint\",
 *                     \"description\": \"Returns 200 OK if the service is healthy\",
 *                     \"operationId\": \"health\",
 *                     \"tags\": [\"sequencer\"],
 *                     \"responses\": {
 *                         \"200\": {
 *                             \"description\": \"Service is healthy\"
 *                         }
 *                     }
 *                 }
 *             }
 *         },
 *         \"components\": {
 *             \"securitySchemes\": {
 *                 \"BearerAuth\": {
 *                     \"type\": \"http\",
 *                     \"scheme\": \"bearer\"
 *                 }
 *             },
 *             \"schemas\": {
 *                 \"SequenceRequest\": {
 *                     \"type\": \"object\",
 *                     \"required\": [\"domain\", \"request_id\"],
 *                     \"properties\": {
 *                         \"domain\": {
 *                             \"type\": \"string\",
 *                             \"description\": \"Domain identifier for sequencing requests\"
 *                         },
 *                         \"request_id\": {
 *                             \"type\": \"string\",
 *                             \"description\": \"Unique identifier for this request\"
 *                         }
 *                     }
 *                 },
 *                 \"DoneRequest\": {
 *                     \"type\": \"object\",
 *                     \"required\": [\"domain\"],
 *                     \"properties\": {
 *                         \"domain\": {
 *                             \"type\": \"string\",
 *                             \"description\": \"Domain identifier to mark as done\"
 *                         }
 *                     }
 *                 },
 *                 \"ErrorResponse\": {
 *                     \"type\": \"object\",
 *                     \"required\": [\"message\"],
 *                     \"properties\": {
 *                         \"message\": {
 *                             \"type\": \"string\",
 *                             \"description\": \"Error message\"
 *                         }
 *                     }
 *                 }
 *             }
 *         },
 *         \"tags\": [
 *             {
 *                 \"name\": \"sequencer\",
 *                 \"description\": \"Sequencer API endpoints\"
 *             }
 *         ]
 *     });
 *
 *     Json(openapi_spec)
 * }
 *
 * //
 * // ------------------
 * // Axum server
 * // ------------------
 * //
 * #[derive(Clone)]
 * struct AppState {
 *     sequencer: Arc<Sequencer>,
 *     api_key_store: ApiKeyStore,
 * }
 *
 * /// Handler to sequence a request for a specific domain",
 *                         "operationId": "sequence",
 *                         "tags": [
 *                             "sequencer"
 *                         ],
 *                         "security": [
 *                             {
 *                                 "BearerAuth": []
 *                             }
 *                         ],
 *                         "requestBody": {
 *                             "required": true,
 *                             "content": {
 *                                 "application/json": {
 *                                     "schema": {
 *                                         "$ref": "#/components/schemas/SequenceRequest"
 *                                     }
 *                                 }
 *                             }
 *                         },
 *                         "responses": {
 *                             "200": {
 *                                 "description": "Successful sequence operation",
 *                                 "content": {
 *                                     "text/plain": {
 *                                         "schema": {
 *                                             "type": "string",
 *                                             "example": "OK"
 *                                         }
 *                                     }
 *                                 }
 *                             },
 *                             "401": {
 *                                 "description": "Unauthorized - Invalid or missing API key",
 *                                 "content": {
 *                                     "application/json": {
 *                                         "schema": {
 *                                             "$ref": "#/components/schemas/ErrorResponse"
 *                                         }
 *                                     }
 *                                 }
 *                             }
 *                         }
 *                     }
 *                 },
 *                 "/done": {
 *                     "post": {
 *                         "summary": "Done operation",
 *                         "description": "Wait until it's our turn for `domain`.
 *     pub async fn sequence(&self, domain: &str, request_id: &str) {
 *         let domain = domain.to_owned();
 *         let request_id = request_id.to_owned();
 *
 *         let mut map = self.domain_queues.lock().await;
 *         let queue = map.entry(domain.clone()).or_insert(DomainQueue {
 *             active: false,
 *             waiting: VecDeque::new(),
 *         });
 *
 *         if !queue.active {
 *             queue.active = true;
 *             println!(\"[Sequencer] Domain={}, RequestId={} is now active\", domain, request_id);
 *         } else {
 *             println!(\"[Sequencer] Domain={}, RequestId={} is enqueued\", domain, request_id);
 *             let (tx, rx) = oneshot::channel();
 *             queue.waiting.push_back(tx);
 *             drop(map);
 *
 *             // Wait until unblocked by .done()
 *             let _ = rx.await;
 *             println!(\"[Sequencer] Domain={}, RequestId={} is now active\", domain, request_id);
 *         }
 *     }
 *
 *     /// Signal that the active request is done for `domain`. If another is waiting,
 *     /// that one is unblocked and becomes active.
 *     pub async fn done(&self, domain: &str) {
 *         let domain = domain.to_owned();
 *         let mut map = self.domain_queues.lock().await;
 *         if let Some(queue) = map.get_mut(&domain) {
 *             if let Some(tx) = queue.waiting.pop_front() {
 *                 let _ = tx.send(());
 *             } else {
 *                 // No one waiting; mark domain as idle
 *                 queue.active = false;
 *             }
 *         }
 *     }
 * }
 *
 * //
 * // ------------------
 * // Request/Response Models
 * // ------------------
 * //
 *
 * #[derive(Serialize, Deserialize)]
 * struct ErrorResponse {
 *     message: String,
 * }
 *
 * #[derive(Deserialize, Serialize)]
 * struct SequenceRequest {
 *     domain: String,
 *     request_id: String,
 * }
 *
 * #[derive(Deserialize, Serialize)]
 * struct DoneRequest {
 *     domain: String,
 * }
 *
 * //
 * // ------------------
 * // OpenAPI Specification
 * // ------------------
 * //
 *
 * /// Returns the OpenAPI specification as a JSON object
 * async fn openapi_json() -> Json<serde_json::Value> {
 *     let openapi_spec = serde_json::json!({
 *         \"openapi\": \"3.0.3\",
 *         \"info\": {
 *             \"title\": \"Sequencer API\",
 *             \"description\": \"API for sequencing domain operations\",
 *             \"version\": \"0.1.0\",
 *             \"contact\": {
 *                 \"name\": \"API Support\",
 *                 \"email\": \"support@example.com\"
 *             }
 *         },
 *         \"paths\": {
 *             \"/sequence\": {
 *                 \"post\": {
 *                     \"summary\": \"Sequence a request for a domain\",
 *                     \"description\": \"Request will be queued if there's already an active request for the domain\",
 *                     \"operationId\": \"sequence\",
 *                     \"tags\": [\"sequencer\"],
 *                     \"security\": [{\"BearerAuth\": []}],
 *                     \"requestBody\": {
 *                         \"required\": true,
 *                         \"content\": {
 *                             \"application/json\": {
 *                                 \"schema\": {
 *                                     \"$ref\": \"#/components/schemas/SequenceRequest\"
 *                                 }
 *                             }
 *                         }
 *                     },
 *                     \"responses\": {
 *                         \"200\": {
 *                             \"description\": \"Request has been sequenced\",
 *                             \"content\": {
 *                                 \"text/plain\": {
 *                                     \"schema\": {
 *                                         \"type\": \"string\",
 *                                         \"example\": \"OK\"
 *                                     }
 *                                 }
 *                             }
 *                         },
 *                         \"401\": {
 *                             \"description\": \"Unauthorized - Invalid or missing API key\",
 *                             \"content\": {
 *                                 \"application/json\": {
 *                                     \"schema\": {
 *                                         \"$ref\": \"#/components/schemas/ErrorResponse\"
 *                                     }
 *                                 }
 *                             }
 *                         }
 *                     }
 *                 }
 *             },
 *             \"/done\": {
 *                 \"post\": {
 *                     \"summary\": \"Mark a domain's active request as done\",
 *                     \"description\": \"If other requests are waiting, the next one will become active\",
 *                     \"operationId\": \"done\",
 *                     \"tags\": [\"sequencer\"],
 *                     \"security\": [{\"BearerAuth\": []}],
 *                     \"requestBody\": {
 *                         \"required\": true,
 *                         \"content\": {
 *                             \"application/json\": {
 *                                 \"schema\": {
 *                                     \"$ref\": \"#/components/schemas/DoneRequest\"
 *                                 }
 *                             }
 *                         }
 *                     },
 *                     \"responses\": {
 *                         \"200\": {
 *                             \"description\": \"Domain marked as done\",
 *                             \"content\": {
 *                                 \"text/plain\": {
 *                                     \"schema\": {
 *                                         \"type\": \"string\",
 *                                         \"example\": \"OK\"
 *                                     }
 *                                 }
 *                             }
 *                         },
 *                         \"401\": {
 *                             \"description\": \"Unauthorized - Invalid or missing API key\",
 *                             \"content\": {
 *                                 \"application/json\": {
 *                                     \"schema\": {
 *                                         \"$ref\": \"#/components/schemas/ErrorResponse\"
 *                                     }
 *                                 }
 *                             }
 *                         }
 *                     }
 *                 }
 *             },
 *             \"/health\": {
 *                 \"get\": {
 *                     \"summary\": \"Health check endpoint\",
 *                     \"description\": \"Returns 200 OK if the service is healthy\",
 *                     \"operationId\": \"health\",
 *                     \"tags\": [\"sequencer\"],
 *                     \"responses\": {
 *                         \"200\": {
 *                             \"description\": \"Service is healthy\"
 *                         }
 *                     }
 *                 }
 *             }
 *         },
 *         \"components\": {
 *             \"securitySchemes\": {
 *                 \"BearerAuth\": {
 *                     \"type\": \"http\",
 *                     \"scheme\": \"bearer\"
 *                 }
 *             },
 *             \"schemas\": {
 *                 \"SequenceRequest\": {
 *                     \"type\": \"object\",
 *                     \"required\": [\"domain\", \"request_id\"],
 *                     \"properties\": {
 *                         \"domain\": {
 *                             \"type\": \"string\",
 *                             \"description\": \"Domain identifier for sequencing requests\"
 *                         },
 *                         \"request_id\": {
 *                             \"type\": \"string\",
 *                             \"description\": \"Unique identifier for this request\"
 *                         }
 *                     }
 *                 },
 *                 \"DoneRequest\": {
 *                     \"type\": \"object\",
 *                     \"required\": [\"domain\"],
 *                     \"properties\": {
 *                         \"domain\": {
 *                             \"type\": \"string\",
 *                             \"description\": \"Domain identifier to mark as done\"
 *                         }
 *                     }
 *                 },
 *                 \"ErrorResponse\": {
 *                     \"type\": \"object\",
 *                     \"required\": [\"message\"],
 *                     \"properties\": {
 *                         \"message\": {
 *                             \"type\": \"string\",
 *                             \"description\": \"Error message\"
 *                         }
 *                     }
 *                 }
 *             }
 *         },
 *         \"tags\": [
 *             {
 *                 \"name\": \"sequencer\",
 *                 \"description\": \"Sequencer API endpoints\"
 *             }
 *         ]
 *     });
 *
 *     Json(openapi_spec)
 * }
 *
 * //
 * // ------------------
 * // Axum server
 * // ------------------
 * //
 * #[derive(Clone)]
 * struct AppState {
 *     sequencer: Arc<Sequencer>,
 *     api_key_store: ApiKeyStore,
 * }
 *
 * /// Handler to sequence a request for a specific domain
 */
export function sequencerSequence(
  client: ChopinCore,
  request: components.SequenceRequest,
  options?: RequestOptions,
): APIPromise<
  Result<
    string,
    | errors.ErrorResponse
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: ChopinCore,
  request: components.SequenceRequest,
  options?: RequestOptions,
): Promise<
  [
    Result<
      string,
      | errors.ErrorResponse
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) => components.SequenceRequest$outboundSchema.parse(value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = encodeJSON("body", payload, { explode: true });

  const path = pathToFunc("/sequence")();

  const headers = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "text/plain",
  }));

  const secConfig = await extractSecurity(client._options.bearerAuth);
  const securityInput = secConfig == null ? {} : { bearerAuth: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "sequence",
    oAuth2Scopes: [],

    resolvedSecurity: requestSecurity,

    securitySource: client._options.bearerAuth,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: ["401", "4XX", "5XX"],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    string,
    | errors.ErrorResponse
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.text(200, z.string()),
    M.jsonErr(401, errors.ErrorResponse$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
