/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { ChopinCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope, mcpScopes } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$oraclePostApiV1ContextJson } from "./tools/oraclePostApiV1ContextJson.js";
import { tool$oraclePostApiV1ContextMultipart } from "./tools/oraclePostApiV1ContextMultipart.js";
import { tool$oraclePostApiV1ContextRaw } from "./tools/oraclePostApiV1ContextRaw.js";
import { tool$sequencerPostApiV1RequestJson } from "./tools/sequencerPostApiV1RequestJson.js";
import { tool$sequencerPostApiV1RequestMultipart } from "./tools/sequencerPostApiV1RequestMultipart.js";
import { tool$sequencerPostApiV1RequestRaw } from "./tools/sequencerPostApiV1RequestRaw.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL: string;
  bearerAuth?: SDKOptions["bearerAuth"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "Chopin",
    version: "0.2.1",
  });

  const client = new ChopinCore({
    bearerAuth: deps.bearerAuth,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
  });

  const scopes = new Set(deps.scopes ?? mcpScopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const register = { tool, resource, resourceTemplate };
  void register; // suppress unused warnings

  tool(tool$oraclePostApiV1ContextJson);
  tool(tool$oraclePostApiV1ContextMultipart);
  tool(tool$oraclePostApiV1ContextRaw);
  tool(tool$sequencerPostApiV1RequestJson);
  tool(tool$sequencerPostApiV1RequestMultipart);
  tool(tool$sequencerPostApiV1RequestRaw);

  return server;
}
