/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { ChopinCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { MCPScope, mcpScopes } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$sequencerDone } from "./tools/sequencerDone.js";
import { tool$sequencerHealth } from "./tools/sequencerHealth.js";
import { tool$sequencerOpenapiJson } from "./tools/sequencerOpenapiJson.js";
import { tool$sequencerSequence } from "./tools/sequencerSequence.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  scopes?: MCPScope[] | undefined;
  serverURL: string;
  bearerAuth?: SDKOptions["bearerAuth"] | undefined;
}) {
  const server = new McpServer({
    name: "Chopin",
    version: "0.0.2",
  });

  const client = new ChopinCore({
    bearerAuth: deps.bearerAuth,
    serverURL: deps.serverURL,
  });
  const scopes = new Set(deps.scopes ?? mcpScopes);
  const tool = createRegisterTool(deps.logger, server, client, scopes);

  tool(tool$sequencerSequence);
  tool(tool$sequencerDone);
  tool(tool$sequencerHealth);
  tool(tool$sequencerOpenapiJson);

  return server;
}
