/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiV1ContextMultipartRequestBody = {
  /**
   * Nonce of the request
   */
  requestNonce: string;
  /**
   * Context value to store
   */
  value: string;
};

/** @internal */
export const PostApiV1ContextMultipartRequestBody$inboundSchema: z.ZodType<
  PostApiV1ContextMultipartRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  requestNonce: z.string(),
  value: z.string(),
});

/** @internal */
export type PostApiV1ContextMultipartRequestBody$Outbound = {
  requestNonce: string;
  value: string;
};

/** @internal */
export const PostApiV1ContextMultipartRequestBody$outboundSchema: z.ZodType<
  PostApiV1ContextMultipartRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiV1ContextMultipartRequestBody
> = z.object({
  requestNonce: z.string(),
  value: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiV1ContextMultipartRequestBody$ {
  /** @deprecated use `PostApiV1ContextMultipartRequestBody$inboundSchema` instead. */
  export const inboundSchema =
    PostApiV1ContextMultipartRequestBody$inboundSchema;
  /** @deprecated use `PostApiV1ContextMultipartRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    PostApiV1ContextMultipartRequestBody$outboundSchema;
  /** @deprecated use `PostApiV1ContextMultipartRequestBody$Outbound` instead. */
  export type Outbound = PostApiV1ContextMultipartRequestBody$Outbound;
}

export function postApiV1ContextMultipartRequestBodyToJSON(
  postApiV1ContextMultipartRequestBody: PostApiV1ContextMultipartRequestBody,
): string {
  return JSON.stringify(
    PostApiV1ContextMultipartRequestBody$outboundSchema.parse(
      postApiV1ContextMultipartRequestBody,
    ),
  );
}

export function postApiV1ContextMultipartRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1ContextMultipartRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiV1ContextMultipartRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1ContextMultipartRequestBody' from JSON`,
  );
}
