/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * HTTP headers
 */
export type PostApiRequestMultipartHeaders = {};

export type PostApiRequestMultipartRequestBody = {
  /**
   * The request body content
   */
  body: string;
  /**
   * HTTP headers
   */
  headers: PostApiRequestMultipartHeaders;
  /**
   * HTTP method (GET, POST, PUT, etc.)
   */
  method: string;
  /**
   * Complete URL of the request
   */
  url: string;
};

/** @internal */
export const PostApiRequestMultipartHeaders$inboundSchema: z.ZodType<
  PostApiRequestMultipartHeaders,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type PostApiRequestMultipartHeaders$Outbound = {};

/** @internal */
export const PostApiRequestMultipartHeaders$outboundSchema: z.ZodType<
  PostApiRequestMultipartHeaders$Outbound,
  z.ZodTypeDef,
  PostApiRequestMultipartHeaders
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiRequestMultipartHeaders$ {
  /** @deprecated use `PostApiRequestMultipartHeaders$inboundSchema` instead. */
  export const inboundSchema = PostApiRequestMultipartHeaders$inboundSchema;
  /** @deprecated use `PostApiRequestMultipartHeaders$outboundSchema` instead. */
  export const outboundSchema = PostApiRequestMultipartHeaders$outboundSchema;
  /** @deprecated use `PostApiRequestMultipartHeaders$Outbound` instead. */
  export type Outbound = PostApiRequestMultipartHeaders$Outbound;
}

export function postApiRequestMultipartHeadersToJSON(
  postApiRequestMultipartHeaders: PostApiRequestMultipartHeaders,
): string {
  return JSON.stringify(
    PostApiRequestMultipartHeaders$outboundSchema.parse(
      postApiRequestMultipartHeaders,
    ),
  );
}

export function postApiRequestMultipartHeadersFromJSON(
  jsonString: string,
): SafeParseResult<PostApiRequestMultipartHeaders, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiRequestMultipartHeaders$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiRequestMultipartHeaders' from JSON`,
  );
}

/** @internal */
export const PostApiRequestMultipartRequestBody$inboundSchema: z.ZodType<
  PostApiRequestMultipartRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  body: z.string(),
  headers: z.lazy(() => PostApiRequestMultipartHeaders$inboundSchema),
  method: z.string(),
  url: z.string(),
});

/** @internal */
export type PostApiRequestMultipartRequestBody$Outbound = {
  body: string;
  headers: PostApiRequestMultipartHeaders$Outbound;
  method: string;
  url: string;
};

/** @internal */
export const PostApiRequestMultipartRequestBody$outboundSchema: z.ZodType<
  PostApiRequestMultipartRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiRequestMultipartRequestBody
> = z.object({
  body: z.string(),
  headers: z.lazy(() => PostApiRequestMultipartHeaders$outboundSchema),
  method: z.string(),
  url: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiRequestMultipartRequestBody$ {
  /** @deprecated use `PostApiRequestMultipartRequestBody$inboundSchema` instead. */
  export const inboundSchema = PostApiRequestMultipartRequestBody$inboundSchema;
  /** @deprecated use `PostApiRequestMultipartRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    PostApiRequestMultipartRequestBody$outboundSchema;
  /** @deprecated use `PostApiRequestMultipartRequestBody$Outbound` instead. */
  export type Outbound = PostApiRequestMultipartRequestBody$Outbound;
}

export function postApiRequestMultipartRequestBodyToJSON(
  postApiRequestMultipartRequestBody: PostApiRequestMultipartRequestBody,
): string {
  return JSON.stringify(
    PostApiRequestMultipartRequestBody$outboundSchema.parse(
      postApiRequestMultipartRequestBody,
    ),
  );
}

export function postApiRequestMultipartRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiRequestMultipartRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiRequestMultipartRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiRequestMultipartRequestBody' from JSON`,
  );
}
