/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * HTTP headers
 */
export type PostApiV1RequestJsonHeaders = {};

export type PostApiV1RequestJsonRequestBody = {
  /**
   * Complete URL of the request
   */
  url: string;
  /**
   * HTTP method (GET, POST, PUT, etc.)
   */
  method: string;
  /**
   * HTTP headers
   */
  headers: PostApiV1RequestJsonHeaders;
  /**
   * The request body content
   */
  body: string;
};

/** @internal */
export const PostApiV1RequestJsonHeaders$inboundSchema: z.ZodType<
  PostApiV1RequestJsonHeaders,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type PostApiV1RequestJsonHeaders$Outbound = {};

/** @internal */
export const PostApiV1RequestJsonHeaders$outboundSchema: z.ZodType<
  PostApiV1RequestJsonHeaders$Outbound,
  z.ZodTypeDef,
  PostApiV1RequestJsonHeaders
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiV1RequestJsonHeaders$ {
  /** @deprecated use `PostApiV1RequestJsonHeaders$inboundSchema` instead. */
  export const inboundSchema = PostApiV1RequestJsonHeaders$inboundSchema;
  /** @deprecated use `PostApiV1RequestJsonHeaders$outboundSchema` instead. */
  export const outboundSchema = PostApiV1RequestJsonHeaders$outboundSchema;
  /** @deprecated use `PostApiV1RequestJsonHeaders$Outbound` instead. */
  export type Outbound = PostApiV1RequestJsonHeaders$Outbound;
}

export function postApiV1RequestJsonHeadersToJSON(
  postApiV1RequestJsonHeaders: PostApiV1RequestJsonHeaders,
): string {
  return JSON.stringify(
    PostApiV1RequestJsonHeaders$outboundSchema.parse(
      postApiV1RequestJsonHeaders,
    ),
  );
}

export function postApiV1RequestJsonHeadersFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1RequestJsonHeaders, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1RequestJsonHeaders$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1RequestJsonHeaders' from JSON`,
  );
}

/** @internal */
export const PostApiV1RequestJsonRequestBody$inboundSchema: z.ZodType<
  PostApiV1RequestJsonRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string(),
  method: z.string(),
  headers: z.lazy(() => PostApiV1RequestJsonHeaders$inboundSchema),
  body: z.string(),
});

/** @internal */
export type PostApiV1RequestJsonRequestBody$Outbound = {
  url: string;
  method: string;
  headers: PostApiV1RequestJsonHeaders$Outbound;
  body: string;
};

/** @internal */
export const PostApiV1RequestJsonRequestBody$outboundSchema: z.ZodType<
  PostApiV1RequestJsonRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiV1RequestJsonRequestBody
> = z.object({
  url: z.string(),
  method: z.string(),
  headers: z.lazy(() => PostApiV1RequestJsonHeaders$outboundSchema),
  body: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiV1RequestJsonRequestBody$ {
  /** @deprecated use `PostApiV1RequestJsonRequestBody$inboundSchema` instead. */
  export const inboundSchema = PostApiV1RequestJsonRequestBody$inboundSchema;
  /** @deprecated use `PostApiV1RequestJsonRequestBody$outboundSchema` instead. */
  export const outboundSchema = PostApiV1RequestJsonRequestBody$outboundSchema;
  /** @deprecated use `PostApiV1RequestJsonRequestBody$Outbound` instead. */
  export type Outbound = PostApiV1RequestJsonRequestBody$Outbound;
}

export function postApiV1RequestJsonRequestBodyToJSON(
  postApiV1RequestJsonRequestBody: PostApiV1RequestJsonRequestBody,
): string {
  return JSON.stringify(
    PostApiV1RequestJsonRequestBody$outboundSchema.parse(
      postApiV1RequestJsonRequestBody,
    ),
  );
}

export function postApiV1RequestJsonRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1RequestJsonRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1RequestJsonRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1RequestJsonRequestBody' from JSON`,
  );
}
