/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiV1RequestRawResponse =
  | any
  | Uint8Array
  | string
  | string
  | any
  | string;

/** @internal */
export const PostApiV1RequestRawResponse$inboundSchema: z.ZodType<
  PostApiV1RequestRawResponse,
  z.ZodTypeDef,
  unknown
> = z.union([z.any(), b64$.zodInbound, z.string(), z.any(), z.string()]);

/** @internal */
export type PostApiV1RequestRawResponse$Outbound =
  | any
  | Uint8Array
  | string
  | any
  | string;

/** @internal */
export const PostApiV1RequestRawResponse$outboundSchema: z.ZodType<
  PostApiV1RequestRawResponse$Outbound,
  z.ZodTypeDef,
  PostApiV1RequestRawResponse
> = z.union([z.any(), b64$.zodOutbound, z.string(), z.any(), z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiV1RequestRawResponse$ {
  /** @deprecated use `PostApiV1RequestRawResponse$inboundSchema` instead. */
  export const inboundSchema = PostApiV1RequestRawResponse$inboundSchema;
  /** @deprecated use `PostApiV1RequestRawResponse$outboundSchema` instead. */
  export const outboundSchema = PostApiV1RequestRawResponse$outboundSchema;
  /** @deprecated use `PostApiV1RequestRawResponse$Outbound` instead. */
  export type Outbound = PostApiV1RequestRawResponse$Outbound;
}

export function postApiV1RequestRawResponseToJSON(
  postApiV1RequestRawResponse: PostApiV1RequestRawResponse,
): string {
  return JSON.stringify(
    PostApiV1RequestRawResponse$outboundSchema.parse(
      postApiV1RequestRawResponse,
    ),
  );
}

export function postApiV1RequestRawResponseFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1RequestRawResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1RequestRawResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1RequestRawResponse' from JSON`,
  );
}
