/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * HTTP headers
 */
export type PostApiV1RequestMultipartHeaders = {};

export type PostApiV1RequestMultipartRequestBody = {
  /**
   * The request body content
   */
  body: string;
  /**
   * HTTP headers
   */
  headers: PostApiV1RequestMultipartHeaders;
  /**
   * HTTP method (GET, POST, PUT, etc.)
   */
  method: string;
  /**
   * Complete URL of the request
   */
  url: string;
};

/** @internal */
export const PostApiV1RequestMultipartHeaders$inboundSchema: z.ZodType<
  PostApiV1RequestMultipartHeaders,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type PostApiV1RequestMultipartHeaders$Outbound = {};

/** @internal */
export const PostApiV1RequestMultipartHeaders$outboundSchema: z.ZodType<
  PostApiV1RequestMultipartHeaders$Outbound,
  z.ZodTypeDef,
  PostApiV1RequestMultipartHeaders
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiV1RequestMultipartHeaders$ {
  /** @deprecated use `PostApiV1RequestMultipartHeaders$inboundSchema` instead. */
  export const inboundSchema = PostApiV1RequestMultipartHeaders$inboundSchema;
  /** @deprecated use `PostApiV1RequestMultipartHeaders$outboundSchema` instead. */
  export const outboundSchema = PostApiV1RequestMultipartHeaders$outboundSchema;
  /** @deprecated use `PostApiV1RequestMultipartHeaders$Outbound` instead. */
  export type Outbound = PostApiV1RequestMultipartHeaders$Outbound;
}

export function postApiV1RequestMultipartHeadersToJSON(
  postApiV1RequestMultipartHeaders: PostApiV1RequestMultipartHeaders,
): string {
  return JSON.stringify(
    PostApiV1RequestMultipartHeaders$outboundSchema.parse(
      postApiV1RequestMultipartHeaders,
    ),
  );
}

export function postApiV1RequestMultipartHeadersFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1RequestMultipartHeaders, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1RequestMultipartHeaders$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1RequestMultipartHeaders' from JSON`,
  );
}

/** @internal */
export const PostApiV1RequestMultipartRequestBody$inboundSchema: z.ZodType<
  PostApiV1RequestMultipartRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  body: z.string(),
  headers: z.lazy(() => PostApiV1RequestMultipartHeaders$inboundSchema),
  method: z.string(),
  url: z.string(),
});

/** @internal */
export type PostApiV1RequestMultipartRequestBody$Outbound = {
  body: string;
  headers: PostApiV1RequestMultipartHeaders$Outbound;
  method: string;
  url: string;
};

/** @internal */
export const PostApiV1RequestMultipartRequestBody$outboundSchema: z.ZodType<
  PostApiV1RequestMultipartRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiV1RequestMultipartRequestBody
> = z.object({
  body: z.string(),
  headers: z.lazy(() => PostApiV1RequestMultipartHeaders$outboundSchema),
  method: z.string(),
  url: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiV1RequestMultipartRequestBody$ {
  /** @deprecated use `PostApiV1RequestMultipartRequestBody$inboundSchema` instead. */
  export const inboundSchema =
    PostApiV1RequestMultipartRequestBody$inboundSchema;
  /** @deprecated use `PostApiV1RequestMultipartRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    PostApiV1RequestMultipartRequestBody$outboundSchema;
  /** @deprecated use `PostApiV1RequestMultipartRequestBody$Outbound` instead. */
  export type Outbound = PostApiV1RequestMultipartRequestBody$Outbound;
}

export function postApiV1RequestMultipartRequestBodyToJSON(
  postApiV1RequestMultipartRequestBody: PostApiV1RequestMultipartRequestBody,
): string {
  return JSON.stringify(
    PostApiV1RequestMultipartRequestBody$outboundSchema.parse(
      postApiV1RequestMultipartRequestBody,
    ),
  );
}

export function postApiV1RequestMultipartRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1RequestMultipartRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiV1RequestMultipartRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1RequestMultipartRequestBody' from JSON`,
  );
}
