/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * HTTP headers
 */
export type PostApiRequestJsonHeaders = {};

export type PostApiRequestJsonRequestBody = {
  /**
   * Complete URL of the request
   */
  url: string;
  /**
   * HTTP method (GET, POST, PUT, etc.)
   */
  method: string;
  /**
   * HTTP headers
   */
  headers: PostApiRequestJsonHeaders;
  /**
   * The request body content
   */
  body: string;
};

/** @internal */
export const PostApiRequestJsonHeaders$inboundSchema: z.ZodType<
  PostApiRequestJsonHeaders,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type PostApiRequestJsonHeaders$Outbound = {};

/** @internal */
export const PostApiRequestJsonHeaders$outboundSchema: z.ZodType<
  PostApiRequestJsonHeaders$Outbound,
  z.ZodTypeDef,
  PostApiRequestJsonHeaders
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiRequestJsonHeaders$ {
  /** @deprecated use `PostApiRequestJsonHeaders$inboundSchema` instead. */
  export const inboundSchema = PostApiRequestJsonHeaders$inboundSchema;
  /** @deprecated use `PostApiRequestJsonHeaders$outboundSchema` instead. */
  export const outboundSchema = PostApiRequestJsonHeaders$outboundSchema;
  /** @deprecated use `PostApiRequestJsonHeaders$Outbound` instead. */
  export type Outbound = PostApiRequestJsonHeaders$Outbound;
}

export function postApiRequestJsonHeadersToJSON(
  postApiRequestJsonHeaders: PostApiRequestJsonHeaders,
): string {
  return JSON.stringify(
    PostApiRequestJsonHeaders$outboundSchema.parse(postApiRequestJsonHeaders),
  );
}

export function postApiRequestJsonHeadersFromJSON(
  jsonString: string,
): SafeParseResult<PostApiRequestJsonHeaders, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiRequestJsonHeaders$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiRequestJsonHeaders' from JSON`,
  );
}

/** @internal */
export const PostApiRequestJsonRequestBody$inboundSchema: z.ZodType<
  PostApiRequestJsonRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string(),
  method: z.string(),
  headers: z.lazy(() => PostApiRequestJsonHeaders$inboundSchema),
  body: z.string(),
});

/** @internal */
export type PostApiRequestJsonRequestBody$Outbound = {
  url: string;
  method: string;
  headers: PostApiRequestJsonHeaders$Outbound;
  body: string;
};

/** @internal */
export const PostApiRequestJsonRequestBody$outboundSchema: z.ZodType<
  PostApiRequestJsonRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiRequestJsonRequestBody
> = z.object({
  url: z.string(),
  method: z.string(),
  headers: z.lazy(() => PostApiRequestJsonHeaders$outboundSchema),
  body: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiRequestJsonRequestBody$ {
  /** @deprecated use `PostApiRequestJsonRequestBody$inboundSchema` instead. */
  export const inboundSchema = PostApiRequestJsonRequestBody$inboundSchema;
  /** @deprecated use `PostApiRequestJsonRequestBody$outboundSchema` instead. */
  export const outboundSchema = PostApiRequestJsonRequestBody$outboundSchema;
  /** @deprecated use `PostApiRequestJsonRequestBody$Outbound` instead. */
  export type Outbound = PostApiRequestJsonRequestBody$Outbound;
}

export function postApiRequestJsonRequestBodyToJSON(
  postApiRequestJsonRequestBody: PostApiRequestJsonRequestBody,
): string {
  return JSON.stringify(
    PostApiRequestJsonRequestBody$outboundSchema.parse(
      postApiRequestJsonRequestBody,
    ),
  );
}

export function postApiRequestJsonRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiRequestJsonRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiRequestJsonRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiRequestJsonRequestBody' from JSON`,
  );
}
