/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiContextMultipartRequestBody = {
  /**
   * Nonce of the request
   */
  requestNonce: string;
  /**
   * Context value to store
   */
  value: string;
};

/** @internal */
export const PostApiContextMultipartRequestBody$inboundSchema: z.ZodType<
  PostApiContextMultipartRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  requestNonce: z.string(),
  value: z.string(),
});

/** @internal */
export type PostApiContextMultipartRequestBody$Outbound = {
  requestNonce: string;
  value: string;
};

/** @internal */
export const PostApiContextMultipartRequestBody$outboundSchema: z.ZodType<
  PostApiContextMultipartRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiContextMultipartRequestBody
> = z.object({
  requestNonce: z.string(),
  value: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiContextMultipartRequestBody$ {
  /** @deprecated use `PostApiContextMultipartRequestBody$inboundSchema` instead. */
  export const inboundSchema = PostApiContextMultipartRequestBody$inboundSchema;
  /** @deprecated use `PostApiContextMultipartRequestBody$outboundSchema` instead. */
  export const outboundSchema =
    PostApiContextMultipartRequestBody$outboundSchema;
  /** @deprecated use `PostApiContextMultipartRequestBody$Outbound` instead. */
  export type Outbound = PostApiContextMultipartRequestBody$Outbound;
}

export function postApiContextMultipartRequestBodyToJSON(
  postApiContextMultipartRequestBody: PostApiContextMultipartRequestBody,
): string {
  return JSON.stringify(
    PostApiContextMultipartRequestBody$outboundSchema.parse(
      postApiContextMultipartRequestBody,
    ),
  );
}

export function postApiContextMultipartRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiContextMultipartRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      PostApiContextMultipartRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiContextMultipartRequestBody' from JSON`,
  );
}
