/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiContextJsonRequestBody = {
  /**
   * Nonce of the request
   */
  requestNonce: string;
  /**
   * Context value to store
   */
  value: string;
};

/** @internal */
export const PostApiContextJsonRequestBody$inboundSchema: z.ZodType<
  PostApiContextJsonRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  requestNonce: z.string(),
  value: z.string(),
});

/** @internal */
export type PostApiContextJsonRequestBody$Outbound = {
  requestNonce: string;
  value: string;
};

/** @internal */
export const PostApiContextJsonRequestBody$outboundSchema: z.ZodType<
  PostApiContextJsonRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiContextJsonRequestBody
> = z.object({
  requestNonce: z.string(),
  value: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiContextJsonRequestBody$ {
  /** @deprecated use `PostApiContextJsonRequestBody$inboundSchema` instead. */
  export const inboundSchema = PostApiContextJsonRequestBody$inboundSchema;
  /** @deprecated use `PostApiContextJsonRequestBody$outboundSchema` instead. */
  export const outboundSchema = PostApiContextJsonRequestBody$outboundSchema;
  /** @deprecated use `PostApiContextJsonRequestBody$Outbound` instead. */
  export type Outbound = PostApiContextJsonRequestBody$Outbound;
}

export function postApiContextJsonRequestBodyToJSON(
  postApiContextJsonRequestBody: PostApiContextJsonRequestBody,
): string {
  return JSON.stringify(
    PostApiContextJsonRequestBody$outboundSchema.parse(
      postApiContextJsonRequestBody,
    ),
  );
}

export function postApiContextJsonRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiContextJsonRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiContextJsonRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiContextJsonRequestBody' from JSON`,
  );
}
