/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiV1RequestJsonRequestBody = {
  /**
   * Complete URL of the request
   */
  url: string;
  /**
   * HTTP method (GET, POST, PUT, etc.)
   */
  method: string;
  /**
   * HTTP headers
   */
  headers: { [k: string]: string };
  /**
   * The request body content
   */
  body: string;
};

/** @internal */
export const PostApiV1RequestJsonRequestBody$inboundSchema: z.ZodType<
  PostApiV1RequestJsonRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string(),
  method: z.string(),
  headers: z.record(z.string()),
  body: z.string(),
});

/** @internal */
export type PostApiV1RequestJsonRequestBody$Outbound = {
  url: string;
  method: string;
  headers: { [k: string]: string };
  body: string;
};

/** @internal */
export const PostApiV1RequestJsonRequestBody$outboundSchema: z.ZodType<
  PostApiV1RequestJsonRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiV1RequestJsonRequestBody
> = z.object({
  url: z.string(),
  method: z.string(),
  headers: z.record(z.string()),
  body: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiV1RequestJsonRequestBody$ {
  /** @deprecated use `PostApiV1RequestJsonRequestBody$inboundSchema` instead. */
  export const inboundSchema = PostApiV1RequestJsonRequestBody$inboundSchema;
  /** @deprecated use `PostApiV1RequestJsonRequestBody$outboundSchema` instead. */
  export const outboundSchema = PostApiV1RequestJsonRequestBody$outboundSchema;
  /** @deprecated use `PostApiV1RequestJsonRequestBody$Outbound` instead. */
  export type Outbound = PostApiV1RequestJsonRequestBody$Outbound;
}

export function postApiV1RequestJsonRequestBodyToJSON(
  postApiV1RequestJsonRequestBody: PostApiV1RequestJsonRequestBody,
): string {
  return JSON.stringify(
    PostApiV1RequestJsonRequestBody$outboundSchema.parse(
      postApiV1RequestJsonRequestBody,
    ),
  );
}

export function postApiV1RequestJsonRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1RequestJsonRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1RequestJsonRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1RequestJsonRequestBody' from JSON`,
  );
}
