/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type PostApiV1ContextJsonRequestBody = {
  /**
   * Nonce of the request
   */
  requestNonce: string;
  /**
   * Context value to store
   */
  value: string;
};

/** @internal */
export const PostApiV1ContextJsonRequestBody$inboundSchema: z.ZodType<
  PostApiV1ContextJsonRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  requestNonce: z.string(),
  value: z.string(),
});

/** @internal */
export type PostApiV1ContextJsonRequestBody$Outbound = {
  requestNonce: string;
  value: string;
};

/** @internal */
export const PostApiV1ContextJsonRequestBody$outboundSchema: z.ZodType<
  PostApiV1ContextJsonRequestBody$Outbound,
  z.ZodTypeDef,
  PostApiV1ContextJsonRequestBody
> = z.object({
  requestNonce: z.string(),
  value: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PostApiV1ContextJsonRequestBody$ {
  /** @deprecated use `PostApiV1ContextJsonRequestBody$inboundSchema` instead. */
  export const inboundSchema = PostApiV1ContextJsonRequestBody$inboundSchema;
  /** @deprecated use `PostApiV1ContextJsonRequestBody$outboundSchema` instead. */
  export const outboundSchema = PostApiV1ContextJsonRequestBody$outboundSchema;
  /** @deprecated use `PostApiV1ContextJsonRequestBody$Outbound` instead. */
  export type Outbound = PostApiV1ContextJsonRequestBody$Outbound;
}

export function postApiV1ContextJsonRequestBodyToJSON(
  postApiV1ContextJsonRequestBody: PostApiV1ContextJsonRequestBody,
): string {
  return JSON.stringify(
    PostApiV1ContextJsonRequestBody$outboundSchema.parse(
      postApiV1ContextJsonRequestBody,
    ),
  );
}

export function postApiV1ContextJsonRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<PostApiV1ContextJsonRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PostApiV1ContextJsonRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PostApiV1ContextJsonRequestBody' from JSON`,
  );
}
