/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DoneRequest = {
  /**
   * domain for the DoneRequest
   */
  domain: string;
};

/** @internal */
export const DoneRequest$inboundSchema: z.ZodType<
  DoneRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  domain: z.string(),
});

/** @internal */
export type DoneRequest$Outbound = {
  domain: string;
};

/** @internal */
export const DoneRequest$outboundSchema: z.ZodType<
  DoneRequest$Outbound,
  z.ZodTypeDef,
  DoneRequest
> = z.object({
  domain: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DoneRequest$ {
  /** @deprecated use `DoneRequest$inboundSchema` instead. */
  export const inboundSchema = DoneRequest$inboundSchema;
  /** @deprecated use `DoneRequest$outboundSchema` instead. */
  export const outboundSchema = DoneRequest$outboundSchema;
  /** @deprecated use `DoneRequest$Outbound` instead. */
  export type Outbound = DoneRequest$Outbound;
}

export function doneRequestToJSON(doneRequest: DoneRequest): string {
  return JSON.stringify(DoneRequest$outboundSchema.parse(doneRequest));
}

export function doneRequestFromJSON(
  jsonString: string,
): SafeParseResult<DoneRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DoneRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DoneRequest' from JSON`,
  );
}
