/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SequenceRequest = {
  /**
   * domain for the SequenceRequest
   */
  domain: string;
  /**
   * request_id for the SequenceRequest
   */
  requestId: string;
};

/** @internal */
export const SequenceRequest$inboundSchema: z.ZodType<
  SequenceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  domain: z.string(),
  request_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "request_id": "requestId",
  });
});

/** @internal */
export type SequenceRequest$Outbound = {
  domain: string;
  request_id: string;
};

/** @internal */
export const SequenceRequest$outboundSchema: z.ZodType<
  SequenceRequest$Outbound,
  z.ZodTypeDef,
  SequenceRequest
> = z.object({
  domain: z.string(),
  requestId: z.string(),
}).transform((v) => {
  return remap$(v, {
    requestId: "request_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SequenceRequest$ {
  /** @deprecated use `SequenceRequest$inboundSchema` instead. */
  export const inboundSchema = SequenceRequest$inboundSchema;
  /** @deprecated use `SequenceRequest$outboundSchema` instead. */
  export const outboundSchema = SequenceRequest$outboundSchema;
  /** @deprecated use `SequenceRequest$Outbound` instead. */
  export type Outbound = SequenceRequest$Outbound;
}

export function sequenceRequestToJSON(
  sequenceRequest: SequenceRequest,
): string {
  return JSON.stringify(SequenceRequest$outboundSchema.parse(sequenceRequest));
}

export function sequenceRequestFromJSON(
  jsonString: string,
): SafeParseResult<SequenceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SequenceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SequenceRequest' from JSON`,
  );
}
