/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { oraclePostApiContextRaw } from "../../funcs/oraclePostApiContextRaw.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
};

export const tool$oraclePostApiContextRaw: ToolDefinition<typeof args> = {
  name: "oracle_post-api-context-raw",
  description: `Create a new context entry by request nonce

Creates a new context entry for a request identified by its nonce`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await oraclePostApiContextRaw(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
