/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oraclePostApiV1ContextMultipart } from "../../funcs/oraclePostApiV1ContextMultipart.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiV1ContextMultipartRequestBody$inboundSchema,
};

export const tool$oraclePostApiV1ContextMultipart: ToolDefinition<typeof args> =
  {
    name: "oracle_post-api-v1-context-multipart",
    description: `Create a new context entry by request nonce

Creates a new context entry for a request identified by its nonce`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await oraclePostApiV1ContextMultipart(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(void 0, apiCall);
    },
  };
