/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { sequencerPostApiV1RequestRaw } from "../../funcs/sequencerPostApiV1RequestRaw.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
};

export const tool$sequencerPostApiV1RequestRaw: ToolDefinition<typeof args> = {
  name: "sequencer_post-api-v1-request-raw",
  description: `Sequence an HTTP request

Process an HTTP request through the sequencer`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await sequencerPostApiV1RequestRaw(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
