/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sequencerPostApiV1RequestJson } from "../../funcs/sequencerPostApiV1RequestJson.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiV1RequestJsonRequestBody$inboundSchema,
};

export const tool$sequencerPostApiV1RequestJson: ToolDefinition<typeof args> = {
  name: "sequencer_post-api-v1-request-json",
  description: `Sequence an HTTP request

Process an HTTP request through the sequencer`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await sequencerPostApiV1RequestJson(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
