/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { sequencerPostApiRequestRaw } from "../../funcs/sequencerPostApiRequestRaw.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
};

export const tool$sequencerPostApiRequestRaw: ToolDefinition<typeof args> = {
  name: "sequencer_post-api-request-raw",
  description: `Sequence an HTTP request

Process an HTTP request through the sequencer`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await sequencerPostApiRequestRaw(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
