/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sequencerOpenapiJson } from "../../funcs/sequencerOpenapiJson.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$sequencerOpenapiJson: ToolDefinition = {
  name: "sequencer_openapi-json",
  description: `Openapi_json operation

openapi_json operation`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await sequencerOpenapiJson(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
