/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sequencerPostApiRequestMultipart } from "../../funcs/sequencerPostApiRequestMultipart.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostApiRequestMultipartRequestBody$inboundSchema,
};

export const tool$sequencerPostApiRequestMultipart: ToolDefinition<
  typeof args
> = {
  name: "sequencer_post-api-request-multipart",
  description: `Sequence an HTTP request

Process an HTTP request through the sequencer`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await sequencerPostApiRequestMultipart(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
