/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oraclePostApiV1ContextJson } from "../funcs/oraclePostApiV1ContextJson.js";
import { oraclePostApiV1ContextMultipart } from "../funcs/oraclePostApiV1ContextMultipart.js";
import { oraclePostApiV1ContextRaw } from "../funcs/oraclePostApiV1ContextRaw.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Oracle extends ClientSDK {
  /**
   * Create a new context entry by request nonce
   *
   * @remarks
   * Creates a new context entry for a request identified by its nonce
   */
  async postApiV1ContextJson(
    request: operations.PostApiV1ContextJsonRequestBody,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(oraclePostApiV1ContextJson(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a new context entry by request nonce
   *
   * @remarks
   * Creates a new context entry for a request identified by its nonce
   */
  async postApiV1ContextMultipart(
    request: operations.PostApiV1ContextMultipartRequestBody,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(oraclePostApiV1ContextMultipart(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a new context entry by request nonce
   *
   * @remarks
   * Creates a new context entry for a request identified by its nonce
   */
  async postApiV1ContextRaw(
    request: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(oraclePostApiV1ContextRaw(
      this,
      request,
      options,
    ));
  }
}
