/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { oraclePostApiContextJson } from "../funcs/oraclePostApiContextJson.js";
import { oraclePostApiContextMultipart } from "../funcs/oraclePostApiContextMultipart.js";
import { oraclePostApiContextRaw } from "../funcs/oraclePostApiContextRaw.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Oracle extends ClientSDK {
  /**
   * Create a new context entry by request nonce
   *
   * @remarks
   * Creates a new context entry for a request identified by its nonce
   */
  async postApiContextJson(
    request: operations.PostApiContextJsonRequestBody,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(oraclePostApiContextJson(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a new context entry by request nonce
   *
   * @remarks
   * Creates a new context entry for a request identified by its nonce
   */
  async postApiContextMultipart(
    request: operations.PostApiContextMultipartRequestBody,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(oraclePostApiContextMultipart(
      this,
      request,
      options,
    ));
  }

  /**
   * Create a new context entry by request nonce
   *
   * @remarks
   * Creates a new context entry for a request identified by its nonce
   */
  async postApiContextRaw(
    request: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(oraclePostApiContextRaw(
      this,
      request,
      options,
    ));
  }
}
