/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sequencerPostApiV1RequestJson } from "../funcs/sequencerPostApiV1RequestJson.js";
import { sequencerPostApiV1RequestMultipart } from "../funcs/sequencerPostApiV1RequestMultipart.js";
import { sequencerPostApiV1RequestRaw } from "../funcs/sequencerPostApiV1RequestRaw.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Sequencer extends ClientSDK {
  /**
   * Sequence an HTTP request
   *
   * @remarks
   * Process an HTTP request through the sequencer
   */
  async postApiV1RequestJson(
    request: operations.PostApiV1RequestJsonRequestBody,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(sequencerPostApiV1RequestJson(
      this,
      request,
      options,
    ));
  }

  /**
   * Sequence an HTTP request
   *
   * @remarks
   * Process an HTTP request through the sequencer
   */
  async postApiV1RequestMultipart(
    request: operations.PostApiV1RequestMultipartRequestBody,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(sequencerPostApiV1RequestMultipart(
      this,
      request,
      options,
    ));
  }

  /**
   * Sequence an HTTP request
   *
   * @remarks
   * Process an HTTP request through the sequencer
   */
  async postApiV1RequestRaw(
    request: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(sequencerPostApiV1RequestRaw(
      this,
      request,
      options,
    ));
  }
}
