/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import {
  PostApiV1RequestJsonAcceptEnum,
  sequencerPostApiV1RequestJson,
} from "../funcs/sequencerPostApiV1RequestJson.js";
import {
  PostApiV1RequestMultipartAcceptEnum,
  sequencerPostApiV1RequestMultipart,
} from "../funcs/sequencerPostApiV1RequestMultipart.js";
import {
  PostApiV1RequestRawAcceptEnum,
  sequencerPostApiV1RequestRaw,
} from "../funcs/sequencerPostApiV1RequestRaw.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { PostApiV1RequestJsonAcceptEnum } from "../funcs/sequencerPostApiV1RequestJson.js";

export { PostApiV1RequestMultipartAcceptEnum } from "../funcs/sequencerPostApiV1RequestMultipart.js";

export { PostApiV1RequestRawAcceptEnum } from "../funcs/sequencerPostApiV1RequestRaw.js";

export class Sequencer extends ClientSDK {
  /**
   * Sequence an HTTP request
   *
   * @remarks
   * Process an HTTP request through the sequencer
   */
  async postApiV1RequestJson(
    request: operations.PostApiV1RequestJsonRequestBody,
    options?: RequestOptions & {
      acceptHeaderOverride?: PostApiV1RequestJsonAcceptEnum;
    },
  ): Promise<operations.PostApiV1RequestJsonResponse> {
    return unwrapAsync(sequencerPostApiV1RequestJson(
      this,
      request,
      options,
    ));
  }

  /**
   * Sequence an HTTP request
   *
   * @remarks
   * Process an HTTP request through the sequencer
   */
  async postApiV1RequestMultipart(
    request: operations.PostApiV1RequestMultipartRequestBody,
    options?: RequestOptions & {
      acceptHeaderOverride?: PostApiV1RequestMultipartAcceptEnum;
    },
  ): Promise<operations.PostApiV1RequestMultipartResponse> {
    return unwrapAsync(sequencerPostApiV1RequestMultipart(
      this,
      request,
      options,
    ));
  }

  /**
   * Sequence an HTTP request
   *
   * @remarks
   * Process an HTTP request through the sequencer
   */
  async postApiV1RequestRaw(
    request: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array,
    options?: RequestOptions & {
      acceptHeaderOverride?: PostApiV1RequestRawAcceptEnum;
    },
  ): Promise<operations.PostApiV1RequestRawResponse> {
    return unwrapAsync(sequencerPostApiV1RequestRaw(
      this,
      request,
      options,
    ));
  }
}
