/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sequencerPostApiRequestJson } from "../funcs/sequencerPostApiRequestJson.js";
import { sequencerPostApiRequestMultipart } from "../funcs/sequencerPostApiRequestMultipart.js";
import { sequencerPostApiRequestRaw } from "../funcs/sequencerPostApiRequestRaw.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Sequencer extends ClientSDK {
  /**
   * Sequence an HTTP request
   *
   * @remarks
   * Process an HTTP request through the sequencer
   */
  async postApiRequestJson(
    request: operations.PostApiRequestJsonRequestBody,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(sequencerPostApiRequestJson(
      this,
      request,
      options,
    ));
  }

  /**
   * Sequence an HTTP request
   *
   * @remarks
   * Process an HTTP request through the sequencer
   */
  async postApiRequestMultipart(
    request: operations.PostApiRequestMultipartRequestBody,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(sequencerPostApiRequestMultipart(
      this,
      request,
      options,
    ));
  }

  /**
   * Sequence an HTTP request
   *
   * @remarks
   * Process an HTTP request through the sequencer
   */
  async postApiRequestRaw(
    request: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(sequencerPostApiRequestRaw(
      this,
      request,
      options,
    ));
  }
}
