workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Sequencer API:
        inputs:
            - location: ../openapi/openapi.json
        registry:
            location: registry.speakeasyapi.dev/chopin-framework/workspace/sequencer-api
targets:
    chopin:
        target: typescript
        source: Sequencer API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/chopin-framework/workspace/sequencer-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
